name: aoc2019-haskell
version: 0.1.0.0

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - relude
  - text
  - containers
  - parsec

ghc-options: -Wall -Wextra

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - FlexibleInstances
  - MultiParamTypeClasses
  - UndecidableInstances

executables:
  q1-1:
    main: q1/Part1.hs
    source-dirs: src
  q1-2:
    main: q1/Part2.hs
    source-dirs: src
  q2-1:
    main: q2/Part1.hs
    source-dirs: src
  q2-2:
    main: q2/Part2.hs
    source-dirs: src
  q3-1:
    main: q3/Part1.hs
    source-dirs: src
  q3-2:
    main: q3/Part2.hs
    source-dirs: src
  q4-1:
    main: q4/Part1.hs
    source-dirs: src
  q4-2:
    main: q4/Part2.hs
    source-dirs: src
  q5-1:
    main: q5/Part1.hs
    source-dirs: src
  q5-2:
    main: q5/Part2.hs
    source-dirs: src
  q6-1:
    main: q6/Part1.hs
    source-dirs: src
  q6-2:
    main: q6/Part2.hs
    source-dirs: src
  q7-1:
    main: q7/Part1.hs
    source-dirs: src
  q7-2:
    main: q7/Part2.hs
    source-dirs: src
  q8-1:
    main: q8/Part1.hs
    source-dirs: src
  q8-2:
    main: q8/Part2.hs
    source-dirs: src
  q9-1:
    main: q9/Part1.hs
    source-dirs: src
  q9-2:
    main: q9/Part2.hs
    source-dirs: src
  q10-1:
    main: q10/Part1.hs
    source-dirs: src
  q10-2:
    main: q10/Part2.hs
    source-dirs: src
  q11-1:
    main: q11/Part1.hs
    source-dirs: src
  q11-2:
    main: q11/Part2.hs
    source-dirs: src
