name: aoc2019-haskell
version: 0.1.0.0

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - relude

ghc-options: -Wall -Wextra

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

executables:
  q1-1:
    main: q1/Part1.hs
    source-dirs: src
